/*
Crie sinônimos para que o usuário USER_APP acesse,
 de forma mais simples, as procedures INCLUINDO_PRODUTO e INCLUINDO_DADOS_VENDA,
 bem como as tabelas PRODUTO_EXERCICIO e PRODUTO_VENDA_EXERCICIO.
*/

	CREATE PUBLIC SYNONYM INCLUINDO_PRODUTO FOR USER_DEV.INCLUINDO_PRODUTO;

	CREATE PUBLIC SYNONYM INCLUINDO_DADOS_VENDA FOR USER_DEV.INCLUINDO_DADOS_VENDA;

	CREATE PUBLIC SYNONYM PRODUTO_EXERCICIO FOR USER_DEV.PRODUTO_EXERCICIO;

	CREATE PUBLIC SYNONYM PRODUTO_VENDA_EXERCICIO FOR USER_DEV.PRODUTO_VENDA_EXERCICIO;